### ISSUE TITLE
pypi version not up to date

### ISSUE THREAD

**Issue by vanatteveldt** [relwell/corenlp-xml-lib#5]
First of all, thanks for making this library!

If I install from pypi as per the README, I get an importerror:

```{sh}
$ env/bin/pip install corenlp_xml
Collecting corenlp_xml
[..]
Successfully installed corenlp-xml-1.0.3
$ env/bin/python
[..]
>>> from corenlp_xml.document import Document
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wva/nlpipe/env/lib/python3.5/site-packages/corenlp_xml/document.py", line 7, in <module>
    from dependencies import DependencyGraph
ImportError: No module named 'dependencies'
```

In the code on github, I see that this has been fixed recently, and if I import from github it does work. Could you push the current version to pypi, or is something not working yet?

Thanks!

**Comment by relwell** [comment]
Please let me know if version 1.0.4 does the trick for you.

**Comment by vanatteveldt** [comment]
Works perfectly in python2, for some reason the python3 package isn't updated (https://pypi.python.org/simple/corenlp-xml/ only has `corenlp_xml-1.0.4-py2.7.egg`). Not sure why it made a separate package for only pyython2?

**Comment by relwell** [comment]
Oh I wouldn't know -- I don't support Python 3

**Comment by vanatteveldt** [comment]
Well of course that's your good right, but as far as I can see your code runs fine on python3, and pypi has generic versions of your package for earlier versions. Have you changed the way you push to pypi? If you want I can have a look at how to make sure python3 is also supported?

**Comment by relwell** [comment]
I've built and pushed with Python 3 -- please try again

**Comment by vanatteveldt** [comment]
Works like a charm, thank you very much!
